#!/bin/bash

set -e -x -u


# this is a hack to create a backchannel from the broker to the cell.
# this is why this is not a production release/broker pair.
# do not backchannel to real, shared, and/or dfs volume-drivers.
get_cell_ip ()
{
# get the full diego deployment, it should have IPs in it
taskID=$(curl -I -s -k "https://${BOSH_USERNAME}:${BOSH_PASSWORD}@${BOSH_TARGET}/deployments/cf-warden-diego/vms?format=full" | grep tasks | awk -F "/" '{print $NF}' | tr -d "\r")
# but it redirects to the wrong URL, so fix that and get the task
taskIP=$(curl I -s -k "https://${BOSH_USERNAME}:${BOSH_PASSWORD}@${BOSH_TARGET}/tasks/${taskID}")
# but that's got an asynchronous result endpoint to poll, so wait
sleep 5
# finally get the task result and rip the cell IP out of its json
cellIP=$(curl -s -k "https://${BOSH_USERNAME}:${BOSH_PASSWORD}@${BOSH_TARGET}/tasks/${taskID}/output?type=result" | jq -r 'select(.job_name | contains("cell_z1")) | .ips[]')
}

print_cell_ip_stub ()
{
get_cell_ip
cat > ${PWD}/cell-ip.yml << EOF
---
properties:
  localbroker:
    localdriver-url: http://${cellIP}:9089
EOF
}

source $(pwd)/local-volume-release/scripts/ci/utils.sh
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD
check_param ENVIRONMENT_NAME
check_param DEPLOYMENTS_DIR

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"
localvolume_stubs="${PWD}/${DEPLOYMENTS_DIR}/local-volume/stubs"

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/cf/*.yml \
    > ../generated-manifest-localvolume/cf-deployment.yml
popd

pushd local-volume-release
  print_cell_ip_stub

  cat ${PWD}/cell-ip.yml

  ./templates/generate_manifest.sh aws \
    ../generated-manifest-localvolume/cf-deployment.yml \
    ${localvolume_stubs}/director-uuid.yml \
    ${stubs_path}/localbroker/creds.yml \
    ${PWD}/cell-ip.yml

  mv localvolume-aws-manifest.yml ../generated-manifest-localvolume/localvolume-manifest.yml
popd

