#!/bin/bash

set -e -x

apt-get update -y
apt-get install apt-transport-https ca-certificates -y
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get purge lxc-docker
apt-cache policy docker-engine
apt-get update
apt-get install docker-engine -y
service docker start
docker run hello-world

apt-get install golang -y

cd local-volume-release/

    export PATH=/usr/local/go/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    ./scripts/run-docker-tests
cd -