#!/bin/bash

set -e -x

service docker start

cd local-volume-release/

    export PATH=/usr/local/go/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    ./scripts/run-docker-tests
cd -

service docker stop
