---
name: local-volume
director_uuid: (( merge ))
compilation:
  cloud_properties: {}
  network: local-net
  workers: 1
jobs:
- instances: 1
  log_level: debug
  name: pats-broker
  networks:
  - name: local-net
  resource_pool: local-resourcepool
  templates:
  - name: localbroker
    release: local-volume
  - name: route_registrar
    release: cf
  properties:
    localbroker:
      service-id: pats-local-volume
      service-name: pats-service
      plan-name: pats-plan
      plan-id: pats-plan-id
      data-dir: /var/vcap/store/pats-localbroker
      username: (( merge ))
      password: (( merge ))
    route_registrar:
      routes:
      - name: pats-broker
        port: 8999
        registration_interval: 20s
        tags:
          component: pats-broker
        uris:
        - pats-broker.bosh-lite.com
- instances: 1
  log_level: debug
  name: localbroker
  networks:
  - name: local-net
  resource_pool: local-resourcepool
  templates:
  - name: localbroker
    release: local-volume
  - name: route_registrar
    release: cf
  properties:
    localbroker:
      service-id: local-volume
      service-name: local-volume
      plan-name: free-local-disk
      plan-id: free
    route_registrar:
      routes:
      - name: localbroker
        port: 8999
        registration_interval: 20s
        tags:
          component: localbroker
        uris:
        - localbroker.bosh-lite.com
networks:
- name: local-net
  subnets:
  - cloud_properties: {}
    gateway: 10.244.8.1
    range: 10.244.8.0/24
    static:
    - 10.244.8.2
  type: manual
properties:
  localbroker:
    plan-desc: free local filesystem for bosh-lite
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
releases:
- name: local-volume
  version: latest
- name: cf
  version: latest
resource_pools:
- cloud_properties: {}
  name: local-resourcepool
  network: local-net
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000