#!/bin/bash
set -x -e

release_dir=$(cd $(dirname $0)/.. && pwd)

cat > /tmp/pats_integration_config.json <<EOF
{
  "api": "api.bosh-lite.com",
  "admin_user": "admin",
  "admin_password": "admin",
  "apps_domain": "bosh-lite.com",
  "skip_ssl_validation": true,
  "use_http": true,
  "backend": "diego",
  "service_name": "local-volume",
  "plan_name": "free-local-disk",
  "broker_url": "http://localbroker.bosh-lite.com",
  "broker_user": "admin",
  "broker_password": "admin"
}
EOF

TEST_APPLICATION_PATH=${release_dir}/src/code.cloudfoundry.org/persi-acceptance-tests/assets/pora/ \
CONFIG=/tmp/pats_integration_config.json \
ginkgo --slowSpecThreshold=300 -p ${release_dir}/src/code.cloudfoundry.org/persi-acceptance-tests
